// <auto-generated />
namespace ExileRota.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateRotationtablewithonetoonerelationCreatoruserIdandmanytomanyrelationMembersuserId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateRotationtablewithonetoonerelationCreatoruserIdandmanytomanyrelationMembersuserId));
        
        string IMigrationMetadata.Id
        {
            get { return "201903202039363_Create Rotation table with one-to-one relation (Creator - userId) and many-to-many relation (Members - userId)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
