// <auto-generated />
namespace ExileRota.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedRotationtablewithonetooneCreatorrelationandmanytomanymembesrrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRotationtablewithonetooneCreatorrelationandmanytomanymembesrrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201903161946401_Added Rotation table with one-to-one Creator relation and many-to-many membesr relation."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
